name: Python CI

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # This will use the latest Python version

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-tk python3-setuptools libjpeg-dev zlib1g-dev libx11-dev libxtst-dev libpng-dev libffi-dev xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt

    - name: List directory structure
      run: |
        ls -R

    - name: Run tests
      run: |
        xvfb-run python -m unittest discover tests -v