name: Python CI

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - master
      - develop

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # This will use the latest Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    needs: setup-and-build
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: |
        python -m unittest discover tests -v